name: aice-magazine-manager
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      # - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
    networks:
      - back-network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
    networks:
      - back-network
    depends_on:
      - elastic
  back:
    build:
      dockerfile: app-back.Dockerfile
    container_name: back
    restart: unless-stopped
    environment:
      - PORT=3200
    ports:
      - 3200:3200
    networks:
      - back-network
      - front-network
    depends_on:
      - elastic
  front:
    build:
      dockerfile: app-front.Dockerfile
    container_name: front
    restart: unless-stopped
    ports:
      - 4200:80
    depends_on:
      - back
    networks:
      - front-network
networks:
  back-network:
    driver: bridge
  front-network:
